import Navbar from '@/components/Navbar'
import './globals.css'
import { Raleway } from 'next/font/google'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Photographies - NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={raleway.className}>
        <Navbar />  
        {children}
      </body>
    </html>
  )
}
